spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
server:
  port: 8506
provider:
  ribbon:
    listOfServers: localhost:8503,localhost:8505